- name: Stop mongod as a service
  service:
    name: mongod
    state: stopped

# Update mongod.conf again but now with security configured
- name: Update mongod.conf
  template: 
    src: mongod.conf.j2
    dest: /etc/mongod.conf

- name: Copy the keyfile for authentication
  copy: 
    src=secret 
    dest={{ mongodb_db_path }}/secret 
    owner=mongod 
    group=mongod 
    mode=0400

- name: Start mongod as a service with security
  service:
    name: mongod
    state: started